export const FETCH_TOURISTS = 'VACINDO/FETCH_TOURISTS';
export const FETCH_PAYMENTS = 'VACINDO/FETCH_PAYMENTS';
export const FETCH_APPDATA = 'VACINDO/FETCH_APPDATA';
export const SET_DESTINATIONS = 'VACINDO/SET_DESTINATIONS';
