export const FETCH_USER_DATA = 'VACINDO/FETCH_USER_DATA';
export const ADD_BOOKING = 'VACINDO/ADD_BOOKING';
export const SET_DESTINATIONS = 'VACINDO/SET_DESTINATIONS';
export const SET_BOOKINGS = 'VACINDO/SET_BOOKINGS';
