export const AUTHENTICATE_USER = 'ORION/AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'ORION/DEAUTHENTICATE_USER';
export const AUTHENTICATE_ERROR = 'ORION/AUTHENTICATE_ERROR';
export const FETCH_USER_DATA = 'ORION/FETCH_USER_DATA';
export const SET_USER_ROLE = 'ORION/SET_USER_ROLE';
