export const AUTHENTICATE_USER = 'VACINDO/AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'VACINDO/DEAUTHENTICATE_USER';
export const AUTHENTICATE_ERROR = 'VACINDO/AUTHENTICATE_ERROR';
export const FETCH_USER_DATA = 'VACINDO/FETCH_USER_DATA';
export const SET_USER_ROLE = 'VACINDO/SET_USER_ROLE';
